### ISSUE TITLE
Error using MMseqs2

### ISSUE THREAD

**Issue by veronicamb** [edgardomortiz/Captus#6]
Hello Edgardo,

I'm trying to run MMseqs2 on some of my data and I keep getting this error message:

Traceback (most recent call last):
  File "/home/FCAM/vbueno/miniconda3/envs/captus/bin/captus_assembly", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/FCAM/vbueno/miniconda3/envs/captus/lib/python3.11/site-packages/captus/captus_assembly.py", line 1403, in main
    CaptusAssembly()
  File "/home/FCAM/vbueno/miniconda3/envs/captus/lib/python3.11/site-packages/captus/captus_assembly.py", line 90, in __init__
    getattr(self, args.command)()
  File "/home/FCAM/vbueno/miniconda3/envs/captus/lib/python3.11/site-packages/captus/captus_assembly.py", line 1061, in extract
    extract(full_command, args)
  File "/home/FCAM/vbueno/miniconda3/envs/captus/lib/python3.11/site-packages/captus/extract.py", line 574, in extract
    log.log(f'{"sensitivity":>{mar}}: {bold(args.sensitivity)}')
                                            ^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'sensitivity'. Did you mean: 'cl_sensitivity'?

Any idea how to fix this?

thank you!

Veronica

**Comment by edgardomortiz** [comment]
Hi Veronica,

I fixed that issue before, be sure to use version 1.0.0. Or re-clone and refresh the repository if you have more copies cloned elsewhere.

Edgardo

**Comment by veronicamb** [comment]
Fantastic!! Thanks Edgardo!
